name: Build Service

on:
  workflow_dispatch:
  pull_request:
    paths-ignore: ['*.md']
    branches: ['main', 'master', 'update/040']
  push:
    paths-ignore: ['*.md']
    branches: ['main', 'master', 'update/040']

jobs:
  build:
    uses: start9labs/shared-workflows/.github/workflows/buildService.yml@master
    secrets:
      DEV_KEY: ${{ secrets.DEV_KEY }}
