name: Release Service

on:
  push:
    tags:
      - 'v*.*'

jobs:
  release:
    uses: start9labs/shared-workflows/.github/workflows/releaseService.yml@master
    with:
      REGISTRY: ${{ vars.REGISTRY }} # Optional. Defaults to https://alpha-registry-x.start9.com
    secrets:
      DEV_KEY: ${{ secrets.DEV_KEY }} # Required
    permissions:
      contents: write
