name: Release Service

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build-arm:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Prepare StartOS SDK
        uses: k0gen/sdk@v1.3.3

      - name: Checkout services repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build aarch64 image
        run: |
          start-sdk init
          make arm

      - name: Upload aarch64 image
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-image
          path: ./docker-images/aarch64.tar

  build-x86:
    runs-on: ubuntu-24.04
    steps:
      - name: Prepare StartOS SDK
        uses: k0gen/sdk@v1.3.3

      - name: Checkout services repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build x86_64 image
        run: |
          start-sdk init
          make x86

      - name: Upload x86_64 image
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-image
          path: ./docker-images/x86_64.tar

  create-release:
    runs-on: ubuntu-24.04
    needs: [build-arm, build-x86]
    steps:
      - name: Prepare StartOS SDK
        uses: k0gen/sdk@v1.3.3

      - name: Checkout services repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Download aarch64 image
        uses: actions/download-artifact@v4
        with:
          name: aarch64-image
          path: ./docker-images/

      - name: Download x86_64 image
        uses: actions/download-artifact@v4
        with:
          name: x86_64-image
          path: ./docker-images/

      - name: Build the service package
        run: |
          start-sdk init
          make

      - name: Setting package ID and title from the manifest
        id: package
        run: |
          echo "package_id=$(yq -oy ".id" manifest.*)" >> $GITHUB_OUTPUT
          echo "package_title=$(yq -oy ".title" manifest.*)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Generate sha256 checksum
        run: |
          PACKAGE_ID=${{ steps.package.outputs.package_id }}
          sha256sum ${PACKAGE_ID}.s9pk > ${PACKAGE_ID}.s9pk.sha256
        shell: bash

      - name: Generate changelog
        run: |
          PACKAGE_ID=${{ steps.package.outputs.package_id }}
          echo "## What's Changed" > change-log.txt
          yq -oy '.release-notes' manifest.* >> change-log.txt
          echo "## SHA256 Hash" >> change-log.txt
          echo '```' >> change-log.txt
          sha256sum ${PACKAGE_ID}.s9pk >> change-log.txt
          echo '```' >> change-log.txt
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.package.outputs.package_title }} ${{ github.ref_name }}
          prerelease: true
          body_path: change-log.txt
          files: |
            ./${{ steps.package.outputs.package_id }}.s9pk
            ./${{ steps.package.outputs.package_id }}.s9pk.sha256

      - name: Publish to Registry
        env:
          S9USER: ${{ secrets.S9USER }}
          S9PASS: ${{ secrets.S9PASS }}
          S9REGISTRY: ${{ secrets.S9REGISTRY }}
        run: |
          if [[ -z "$S9USER" || -z "$S9PASS" || -z "$S9REGISTRY" ]]; then
            echo "Publish skipped: missing registry credentials."
          else
            start-sdk publish https://$S9USER:$S9PASS@$S9REGISTRY ${{ steps.package.outputs.package_id }}.s9pk
          fi
